language: clojure
lein: 2.8.1
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
branches:
  only:
    - master
    - spa
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
before_script:
  - sudo service postgresql stop # why is this running even though we didn't ask for it?
  - ./dev_db.sh
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
script:
  # verify that we can run unit tests without the database:
  - DATABASE_URL=invalid lein test
  # build cljs and run all tests with coverage tracking:
  - lein run-cloverage
  - lein doo chrome-headless test once
  - lein uberwar
