### Example file for running REMS using a config file with

version: '2'
services:

  app:
    image: cscfi/rems
    mem_reservation: 200m
    mem_limit: 500m
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./simple-config.edn:/rems/config/config.edn

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: rems
      POSTGRES_PASSWORD: remspassword
    mem_reservation: 30m
    mem_limit: 150m
    ports:
      - "127.0.0.1:5432:5432"
