site_name: REMS2 Documentation
pages:
  - Home: index.md
  - User guide:
    - Linking to REMS: linking.md
    - Dictionary: dictionary.md
  - Developer guide:
    - Using the API: usingtheapi.md
    - Architecture: architecture.md
    - Configuration: configuration.md
    - Migrating From REMS1: migrations.md
theme:
  name: readthedocs