site_name: REMS2 Documentation
pages:
  - Home: index.md
  - User guide:
    - Dictionary: dictionary.md
  - Developer guide:
    - Introduction: intro.md
    - Architecture: architecture.md
    - Configuration: configuration.md
    - Migrating From REMS1: migrations.md
theme:
  name: readthedocs