---

- hosts: rems
  become: yes
  tasks:

  - name: Enable EPEL yum repository
    yum:
      name: epel-release

  - name: Install packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - curl
      - wget
      - vim
      - emacs
      - screen

  - name: Install warfile
    copy:
      src: "{{warfile}}"
      dest: /opt/tomcat/webapps/ROOT.war
