---

- hosts: rems
  become: yes
  tasks:

  - name: Enable EPEL yum repository
    yum:
      name: epel-release

  - name: Install packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - curl
      - wget
      - vim
      - emacs
      - screen

  - name: Create directories
    file:
      path: /srv/rems
      state: directory

  # TODO: store revision in warfile, get it from there
  - name: Get git version
    shell: git rev-parse HEAD
    delegate_to: localhost
    become: no
    register: revparse
    check_mode: no

  - name: Install warfile
    copy:
      src: "{{warfile}}"
      dest: "/srv/rems/rems-{{revparse.stdout}}.war"

  - name: Deploy warfile
    file:
      src: "/srv/rems/rems-{{revparse.stdout}}.war"
      dest: /opt/tomcat/webapps/ROOT.war
      state: link
    register: deploy

  - name: Update deploy log
    shell: "echo $(date --rfc-3339=seconds) /srv/rems/rems-{{revparse.stdout}}.war >> /srv/rems/deploy.log"
    when: deploy.changed

  # tomcat doesn't always notice that the jar changed
  - name: Restart tomcat
    service:
      name: tomcat
      state: restarted
    when: deploy.changed
