---

- hosts: rems
  become: yes
  tasks:

  - name: Enable EPEL yum repository
    yum:
      name: epel-release

  - name: Install packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - curl
      - wget
      - vim
      - emacs
      - screen

  - name: Create directories
    file:
      path: /srv/rems
      state: directory

  - name: Get git version
    shell: git rev-parse HEAD
    delegate_to: localhost
    become: no
    register: revparse

  - name: Install warfile
    copy:
      src: "{{warfile}}"
      dest: "/srv/rems/rems-{{revparse.stdout}}.war"

  - name: Deploy warfile
    file:
      src: "/srv/rems/rems-{{revparse.stdout}}.war"
      dest: /opt/tomcat/webapps/ROOT.war
      state: link
