- name: Add Shibboleth yum repository
  shell: "yum-config-manager --add-repo https://download.opensuse.org/repositories/security://shibboleth/CentOS_7/security:shibboleth.repo"
  args:

    creates: /etc/yum.repos.d/shibboleth.repo
- name: Install shibboleth package
  yum:
    name: "shibboleth"
    state: latest

- name: Copy haka test cert
  get_url:
    url: https://confluence.csc.fi/download/attachments/31195585/haka_testi_2015_sha2.crt
    dest: /etc/pki/tls/certs

- name: Configure shibboleth2.xml
  template:
    src: shibboleth2.xml
    dest: /etc/shibboleth/

- name: Configure attribute-map.xml
  template:
    src: attribute-map.xml
    dest: /etc/shibboleth/

- name: Change host cert file to shibd group
  file:
    path: /etc/pki/tls/certs/{{shib_certname}}
    group: shibd

- name: Change host key file to shibd group
  file:
    path: /etc/pki/tls/private/{{shib_keyname}}
    group: shibd

- name: Enable shibboleth service
  service:
    name: shibd
    state: started
    enabled: yes
