---

- hosts: all
  become: yes
  tasks:

  - name: Add Shibboleth yum repository
    shell: "yum-config-manager --add-repo https://download.opensuse.org/repositories/security://shibboleth/CentOS_7/security:shibboleth.repo"
    args:
      creates: /etc/yum.repos.d/shibboleth.repo

  - name: Install packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
      - httpd
      - shibboleth
      - mod_proxy_html
      - mod_ssl

  - name: Copy maintenance page files
    copy: src={{item.src}} dest={{item.dest}}
    with_items:
      - src: '{{maintenance_src}}'
        dest: /var/www/html
      - src: '{{styles_src}}'
        dest: /var/www/html/css
      - src: '{{bg_img_src}}'
        dest: /var/www/html/img

  - name: Copy haka test cert
    get_url:
      url: https://confluence.csc.fi/download/attachments/31195585/haka_testi_2015_sha2.crt
      dest: /etc/pki/tls/certs

  - name: Configure shibboleth2.xml
    template:
      src: shibboleth2.xml
      dest: /etc/shibboleth/

  - name: Configure attribute-map.xml
    template:
      src: attribute-map.xml
      dest: /etc/shibboleth/

  - name: Change host cert file to shibd group
    file:
      path: /etc/pki/tls/certs/{{shib_certname}}
      group: shibd

  - name: Change host key file to shibd group
    file:
      path: /etc/pki/tls/private/{{shib_keyname}}
      group: shibd

  - name: Enable shibboleth service
    service:
      name: shibd
      state: started
      enabled: yes

  - name: Disable pesky welcome.conf
    copy:
      dest: /etc/httpd/conf.d/welcome.conf
      content: "#DON'T REMOVE THIS FILE! IT IS INTENTIONALLY LEFT EMPTY"

  - name: Configure httpd.conf
    template:
      src: httpd.conf
      dest: /etc/httpd/conf/

  - name: Configure ssl.conf
    template:
      src: ssl.conf
      dest: /etc/httpd/conf.d/

  - name: Restore SELinux file context
    command: restorecon -R -v /etc/pki/

  - name: Enable httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Add tomcat group
    group:
      name: tomcat

  - name: Add tomcat user to group tomcat without login option
    user:
      name: tomcat
      group: tomcat
      shell: /bin/nologin
      createhome: no
      home: /opt/tomcat
      system: yes

  - name: Create /opt/tomcat directory with tomcat as group and owner
    file:
      path: /opt/tomcat
      state: directory
      owner: tomcat
      group: tomcat

  - name: Install tomcat
    unarchive:
      src: http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.30/bin/apache-tomcat-8.0.30.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: --strip-components=1

  - name: Copy tomcat.service
    copy:
      src: tomcat.service
      dest: /etc/systemd/system

  - name: Reload Systemd to load the Tomcat unit file
    command: systemctl daemon-reload

  - name: Copy tomcat context.xml
    copy:
      src: context.xml
      dest: /opt/tomcat/conf

  - name: Copy tomcat catalina.properties
    copy:
      src: catalina.properties
      dest: /opt/tomcat/conf

  - name: Delete tomcat examples
    file:
      path: /opt/tomcat/webapps/examples
      state: absent

  - name: Delete tomcat documentation
    file:
      path: /opt/tomcat/webapps/docs
      state: absent

  - name: Change ownership files in /opt/tomcat to tomcat user
    file:
      path: /opt/tomcat
      state: directory
      owner: tomcat
      group: tomcat
      recurse: yes
      mode: 0750

  - name: Enable tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: yes
